---
title: "BishalEDA"
author: "Bishal Karki"
date: "March 27, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      comment = NA)
```

Load the data by running the other code.

```{r sourced functions, fig.height=6, fig.width=9}
#Load the data by running the other code.
source("../ReadData.R")
sheet1 = read_fitbit_data("../../FitBit Data/", sheet = 1)
sheet2 = read_fitbit_data("../../FitBit Data/", sheet = 2)
org_data = merge(sheet2, sheet1, by = c("Date"), all.x = TRUE)
org_data$BMI_centered = org_data$BMI - 18
org_data$MinutesSedentary2 = (org_data$MinutesSedentary - 
                                mean(org_data$MinutesSedentary))
rm(sheet2, sheet1)
library('dplyr')
library('car')
library("vars")
library('tseries')

df1 = org_data[25:nrow(org_data),]

stdize = function(x){ return (x-mean(x))/sd(x)}

# creating new time variables
df1$day_of_week = weekdays(df1$Date)
df1$week = strftime(df1$Date, format = "%V")
df1$month = months(df1$Date)
df1$year =  as.numeric(substr(df1$Date,1,4))
df1$quarters = paste(df1$year,quarters(df1$Date),sep = "-")

dfMonthWeek = df1 %>%  group_by(year, month, day_of_week) %>% 
  summarize(avg_cal_MW = mean(CaloriesBurned),
            avg_sed_min_MW = mean(MinutesSedentary),
            avg_activity_cal_MW = mean(ActivityCalories),
            avg_mins_v_active_MW = mean(MinutesVeryActive))
dfWeek = df1 %>%  group_by(year, month, week) %>% 
  summarize(avg_cal_W = mean(CaloriesBurned),
            avg_sed_min_W = mean(MinutesSedentary),
            avg_activity_cal_W = mean(ActivityCalories),
            avg_mins_v_active_W = mean(MinutesVeryActive))
dfMonth = df1 %>%  group_by(year, month) %>% 
  summarize(avg_cal_M = mean(CaloriesBurned),
            avg_sed_min_M = mean(MinutesSedentary),
            avg_activity_cal_M = mean(ActivityCalories),
            avg_mins_v_active_M = mean(MinutesVeryActive))
dfQuarter = df1 %>%  group_by(quarters) %>% 
  summarize(avg_cal_Q = mean(CaloriesBurned),
            avg_sed_min_Q = mean(MinutesSedentary),
            avg_activity_cal_Q = mean(ActivityCalories),
            avg_mins_v_active_Q = mean(MinutesVeryActive))


dfMerged = merge(merge(merge(merge(df1, dfMonth, by = c("year", "month"), all.x = TRUE),
                 dfMonthWeek, by = c("year", "month", "day_of_week"),
                 all.x = TRUE),
                 dfQuarter, by = c("quarters"), all.x = TRUE),
                 dfWeek, by = c("year", "month", "week"), all.x = TRUE)%>% 
  arrange(Date)


# filtering time by day of week to plot trends
days = unique(dfMerged$day_of_week)
for (ii in days){
  assign(paste0("",ii), dfMerged %>% filter(dfMerged$day_of_week == ii))
}

#ploting at a daily level by days of week
colors = 1:7
lineStyle = 1:7

#plot calories burnt
plot(dfMerged$CaloriesBurned, type = "l", main = "Daily calories burnt", 
     xlab = "Days", ylab = "Calories burnt")

# Daily Plot

plot(Monday$CaloriesBurned, type = "l", col = colors[2], lty = lineStyle[2],
     ylim = c(2200,4000), main = "Day of week calories plot", 
     xlab = "Week numbers", ylab = "Calories burnt")
lines(Sunday$CaloriesBurned, col = colors[1], lty = lineStyle[1])
lines(Tuesday$CaloriesBurned, col = colors[3], lty = lineStyle[3])
lines(Wednesday$CaloriesBurned, col = colors[4], lty = lineStyle[4])
lines(Thursday$CaloriesBurned, col = colors[5], lty = lineStyle[5])
lines(Friday$CaloriesBurned, col = colors[6], lty = lineStyle[6])
lines(Saturday$CaloriesBurned, col = colors[7], lty = lineStyle[7])
legend(100, 4000, legend = days, col = colors, lty = lineStyle, cex = .7)



# Monthly-dayofweek Plot
colors = c("green", "chocolate4", "brown4", "blue4", "azure4", "aquamarine4"
           , "darkviolet")
plot(Sunday$avg_cal_MW, col = "green", type = "l", lty = lineStyle[1],
     ylim = c(2200,4000), main = "Monthly average for day of week calories plot",
     xlab = "Week numbers", ylab = "Calories burnt")
lines(Monday$avg_cal_MW, col = "chocolate4", lty = lineStyle[2])
lines(Tuesday$avg_cal_MW, col = "brown4", lty = lineStyle[3])
lines(Wednesday$avg_cal_MW, col = "blue4", lty = lineStyle[4])
lines(Thursday$avg_cal_MW, col = "azure4", lty = lineStyle[5])
lines(Friday$avg_cal_MW, col = "aquamarine4", lty = lineStyle[6])
lines(Saturday$avg_cal_MW, col = "darkviolet", lty = lineStyle[7])
legend(100,4000, legend = days, col = colors, lty = lineStyle, cex = .7)


#Calories burnt patterns over different averaged times
xlim = c(0,820)
ylim = c(2200,4000)
plot(dfMerged$avg_cal_Q, col = "green", type = "l", lty = lineStyle[1],
     xlim = xlim, ylim = ylim, xlab = "", ylab = "", xaxt = 'n')
par(new = TRUE)
plot(dfMerged$avg_cal_M, col = "red", type = "l", lty = lineStyle[2],
     xlim = xlim, ylim = ylim, xlab = "", ylab = "", xaxt = 'n')
par(new = TRUE)
plot(dfMerged$avg_cal_W, col = "black", type = "l", lty = lineStyle[3], xaxt = 'n',
     xlim = xlim, ylim = ylim, xlab = "Time",
     ylab = " Calories burnt", main = "Patterns in calories burnt")
legend(1, 4000, legend = c("Quarterly", "Monthly", "Weekly"),
       lty = lineStyle[1:3], col = c("green", "red", "black"), cex = .7)


#Sedentary minutes patterns over different averaged times
xlim = c(0,820)
ylim = c(400,900)

plot(dfMerged$MinutesSedentary, type = "l", xlim =  xlim, ylim = ylim)

plot(dfMerged$avg_sed_min_Q, col = "green", type = "l", lty = lineStyle[1],
     xlim = xlim, ylim = ylim, xlab = "", ylab = "", xaxt = 'n')
par(new = TRUE)
plot(dfMerged$avg_sed_min_M, col = "red", type = "l", lty = lineStyle[2],
     xlim = xlim, ylim = ylim, xlab = "", ylab = "", xaxt = 'n')
par(new = TRUE)
plot(dfMerged$avg_sed_min_W, col = "black", type = "l", lty = lineStyle[3], xaxt = 'n',
     xlim = xlim, ylim = ylim, xlab = "Time",
     ylab = " Sedentary minutes", main = "Patterns in sedentary minutes")
legend(1, 900, legend = c("Quarterly", "Monthly", "Weekly"),
       lty = lineStyle[1:3], col = c("green", "red", "black"), cex = .7)

# calories burnt vs minutes sedentary
plot(dfMerged$CaloriesBurned, dfMerged$MinutesSedentary)


#Activity calories patterns over different averaged times
xlim = c(0,820)
ylim = c(400,3000)
plot(dfMerged$avg_activity_cal_Q, col = "green", type = "l", lty = lineStyle[1],
     xlim = xlim, ylim = ylim, xlab = "", ylab = "", xaxt = 'n')
par(new = TRUE)
plot(dfMerged$avg_activity_cal_M, col = "red", type = "l", lty = lineStyle[2],
     xlim = xlim, ylim = ylim, xlab = "", ylab = "", xaxt = 'n')
par(new = TRUE)
plot(dfMerged$avg_activity_cal_W, col = "black", type = "l", lty = lineStyle[3], xaxt = 'n',
     xlim = xlim, ylim = ylim, xlab = "Time",
     ylab = " Activity Calories", main = "Patterns in Activity Calories")
legend(1, 3000, legend = c("Quarterly", "Monthly", "Weekly"),
       lty = lineStyle[1:3], col = c("green", "red", "black"), cex = .7)

#Activity calories patterns over different averaged times
xlim = c(0,820)
ylim = c(0,120)
plot(dfMerged$avg_mins_v_active_Q, col = "green", type = "l", lty = lineStyle[1],
     xlim = xlim, ylim = ylim, xlab = "", ylab = "", xaxt = 'n')
par(new = TRUE)
plot(dfMerged$avg_mins_v_active_M, col = "red", type = "l", lty = lineStyle[2],
     xlim = xlim, ylim = ylim, xlab = "", ylab = "", xaxt = 'n')
par(new = TRUE)
plot(dfMerged$avg_mins_v_active_W, col = "black", type = "l", lty = lineStyle[3], xaxt = 'n',
     xlim = xlim, ylim = ylim, xlab = "Time",
     ylab = "Very Active Minutes", main = "Patterns in Very Active Minutes")
legend(1, 120, legend = c("Quarterly", "Monthly", "Weekly"),
       lty = lineStyle[1:3], col = c("green", "red", "black"), cex = .7)
```


```{r model EDA}
firstModel0 = step(lm(CaloriesBurned ~ MinutesSedentary2 + MinutesLightlyActive +
                  MinutesFairlyActive + 
                    MinutesVeryActive + BMI_centered + ActivityCalories,
                  data = dfMerged),
                  direction = "both")
summary(firstModel0)
vif(firstModel0)

firstModel = step(lm(CaloriesBurned ~ MinutesSedentary2 + MinutesLightlyActive +
                  MinutesFairlyActive + 
                    MinutesVeryActive + BMI_centered,
                  data = dfMerged),
                  direction = "both")
summary(firstModel)
vif(firstModel)

```


```{r model VAR}

# Multivariate model and testing causality
varData = dfMerged[, c("CaloriesBurned", "MinutesSedentary2", 
                              "MinutesLightlyActive", "MinutesFairlyActive",
                              "MinutesVeryActive", "BMI_centered",
                       "MinutesVeryActive", "ActivityCalories")]
varSimple = dfMerged[, c("CaloriesBurned", "MinutesSedentary")]
varSimple2 = dfMerged[, c("CaloriesBurned", "ActivityCalories")]
varSimple3 = dfMerged[, c("CaloriesBurned", "MinutesVeryActive")]
varSimple4 = dfMerged[, c("CaloriesBurned", "MinutesSedentary",
                          "ActivityCalories", "MinutesVeryActive")]


#For simple VAR model
# testing stationarity of data series
for (i in 1:ncol(varData)){
  cat("adf test for", colnames(varData)[i],":\n")
  print(adf.test(ts(varData[i])))
}

#______________________________________________
# all variables stationary - "CaloriesBurned", "MinutesSedentary"
# building model
varModel1 = VAR(varSimple, type = "const", lag.max = 10, ic = 'HQ')
# testing Granger Causality
causality(varModel1, cause = "MinutesSedentary")$Granger
causality(varModel1, cause = "CaloriesBurned")$Granger

varModel1$p

#______________________________________________
# all variables stationary - "CaloriesBurned", "ActivityCalories"
# building model
varModel2 = VAR(varSimple2, type = "const", lag.max = 10, ic = 'HQ')

# testing Granger Causality
causality(varModel2, cause = "ActivityCalories")$Granger
causality(varModel2, cause = "CaloriesBurned")$Granger

varModel2$p
#______________________________________________
# all variables stationary - "CaloriesBurned", "MinutesVeryActive"
# building model
varModel3 = VAR(varSimple3, type = "const", lag.max = 10, ic = 'HQ')
# testing Granger Causality
causality(varModel3, cause = "MinutesVeryActive")$Granger
causality(varModel3, cause = "CaloriesBurned")$Granger

prd = predict(varModel3, n.ahead = 30, ci = 0.95, dumvar = NULL)

varModel3$p

plot(prd)
fanchart(prd, plot.type = c("multiple"))

# #______________________________________________
# # all variables stationary -"CaloriesBurned", "MinutesSedentary", "ActivityCalories", "MinutesVeryActive"
# # building model
# varModel4 = VAR(varSimple, type = "const", lag.max = 10, ic = 'HQ')
# 
# # testing Granger Causality
# causality(varModel, cause = "MinutesSedentary")$Granger
# causality(varModel, cause = "CaloriesBurned")$Granger
# causality(varModel, cause = "MinutesSedentary")$Granger
# causality(varModel, cause = "CaloriesBurned")$Granger

#______________________________________________

### Result - The model concludes that there is not added information in the variable
# for Minutes Sedentary and that it does not help predict the future values of calories burnt
# for quick intro: read https://stats.stackexchange.com/questions/111005/var-and-granger-causality-test




# TESTING BUT NOT SURE ABOUT THE IMPLICATION AND INTERPRETATION SO DO 
# NOT USE IF THE COMMENT IS STILL PRESENT LATER
# all variables stationary except BMI_centered
# Converting BMI_centered to stationary series
# adding one item to have the same length in all series
varData$BMI = c(diff(varData$BMI_centered)[1],diff(varData$BMI_centered))

# building model
# varModel = VAR(varData, type = "const", lag.max = 20, ic = 'HQ')


```
